from django.core.management.base import BaseCommand
from store.models import Product


PRODUCTS = [
    {
        "name": "Nova Pro Headphones",
        "slug": "nova-pro-headphones",
        "price": 349.99,
        "category": "Audio",
        "description": "Immerse yourself in studio-grade sound with the Nova Pro. Featuring 40mm custom drivers, adaptive noise cancellation, and 30-hour battery life wrapped in premium memory foam cushions.",
        "features": [
            "40mm custom neodymium drivers",
            "Adaptive Active Noise Cancellation",
            "30-hour battery life",
            "Bluetooth 5.3 with multipoint",
            "Memory foam ear cushions",
        ],
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80&auto=format",
        "rating": 4.8,
        "reviews_count": 1243,
        "in_stock": True,
        "badge": "Best Seller",
        "stock": 50,
    },
    {
        "name": "Pulse Wireless Earbuds",
        "slug": "pulse-wireless-earbuds",
        "price": 129.99,
        "category": "Audio",
        "description": "Ultra-compact true wireless earbuds with punchy bass, crystal-clear calls, and an IPX5 sweat-proof rating. Your perfect gym companion.",
        "features": [
            "10mm dynamic drivers",
            "IPX5 water resistance",
            "28-hour total battery with case",
            "Touch controls",
            "Transparency mode",
        ],
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80&auto=format",
        "rating": 4.5,
        "reviews_count": 876,
        "in_stock": True,
        "badge": "",
        "stock": 100,
    },
    {
        "name": "Boom 360 Speaker",
        "slug": "boom-360-speaker",
        "price": 199.99,
        "category": "Audio",
        "description": "360-degree room-filling sound in a sleek cylindrical design. Pair two for true stereo. Built-in voice assistant with far-field mics.",
        "features": [
            "360° omnidirectional sound",
            "Stereo pairing support",
            "Built-in voice assistant",
            "16-hour battery life",
            "USB-C fast charging",
        ],
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80&auto=format",
        "rating": 4.6,
        "reviews_count": 534,
        "in_stock": True,
        "badge": "New",
        "stock": 30,
    },
    {
        "name": "Studio Monitor MK3",
        "slug": "studio-monitor-mk3",
        "price": 449.99,
        "category": "Audio",
        "description": "Professional-grade open-back headphones for mixing and mastering. Flat frequency response with exceptional detail retrieval across the entire spectrum.",
        "features": [
            "Open-back planar magnetic drivers",
            "Flat frequency response 10Hz-50kHz",
            "Detachable balanced cable",
            "Lightweight aluminum frame",
            "Velour ear pads",
        ],
        "image_url": "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80&auto=format",
        "rating": 4.9,
        "reviews_count": 312,
        "in_stock": True,
        "badge": "",
        "stock": 15,
    },
    {
        "name": "Bass Drop Portable",
        "slug": "bass-drop-portable",
        "price": 79.99,
        "category": "Audio",
        "description": "Pocket-sized speaker with surprisingly powerful bass. Rugged, waterproof, and ready for any adventure with its carabiner clip design.",
        "features": [
            "IP67 waterproof & dustproof",
            "12-hour battery",
            "Built-in carabiner clip",
            "Dual passive radiators",
            "Speakerphone function",
        ],
        "image_url": "https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600&q=80&auto=format",
        "rating": 4.3,
        "reviews_count": 2105,
        "in_stock": True,
        "badge": "Sale",
        "stock": 200,
    },
    {
        "name": "Apex Ultra Smartwatch",
        "slug": "apex-ultra-smartwatch",
        "price": 499.99,
        "category": "Wearables",
        "description": "The ultimate smartwatch for adventurers. Titanium case, sapphire crystal display, dual-band GPS, and up to 14 days of battery life.",
        "features": [
            '1.5" AMOLED always-on display',
            "Titanium case with sapphire crystal",
            "Dual-band GPS + offline maps",
            "14-day battery life",
            "100m water resistance",
        ],
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&auto=format",
        "rating": 4.7,
        "reviews_count": 891,
        "in_stock": True,
        "badge": "New",
        "stock": 25,
    },
    {
        "name": "FitBand Pro",
        "slug": "fitband-pro",
        "price": 89.99,
        "category": "Wearables",
        "description": "Slim fitness tracker with advanced health monitoring. Track heart rate, blood oxygen, sleep stages, and stress levels 24/7.",
        "features": [
            '0.96" AMOLED touchscreen',
            "24/7 heart rate & SpO2 monitoring",
            "Sleep stage tracking",
            "Stress management score",
            "7-day battery life",
        ],
        "image_url": "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80&auto=format",
        "rating": 4.4,
        "reviews_count": 1567,
        "in_stock": True,
        "badge": "",
        "stock": 80,
    },
    {
        "name": "Chrono Classic",
        "slug": "chrono-classic",
        "price": 299.99,
        "category": "Wearables",
        "description": "A hybrid smartwatch that blends classic analog aesthetics with modern smart features. Genuine leather strap with subtle smart notifications.",
        "features": [
            "Analog watch face with hidden OLED display",
            "Smart notifications",
            "Step & calorie tracking",
            "30-day battery life",
            "Genuine Italian leather strap",
        ],
        "image_url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80&auto=format",
        "rating": 4.6,
        "reviews_count": 423,
        "in_stock": True,
        "badge": "",
        "stock": 40,
    },
    {
        "name": "RunnerX GPS Watch",
        "slug": "runnerx-gps-watch",
        "price": 249.99,
        "category": "Wearables",
        "description": "Purpose-built for serious runners. Precision GPS tracking, VO2 max estimation, training load analysis, and race predictor all on your wrist.",
        "features": [
            "Multi-constellation GPS",
            "VO2 max estimation",
            "Training load & recovery advisor",
            "Race predictor",
            "Music storage (500 songs)",
        ],
        "image_url": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80&auto=format",
        "rating": 4.5,
        "reviews_count": 678,
        "in_stock": False,
        "badge": "",
        "stock": 0,
    },
    {
        "name": "Zen Ring",
        "slug": "zen-ring",
        "price": 199.99,
        "category": "Wearables",
        "description": "The world's thinnest smart ring. Tracks sleep, readiness, and activity without the bulk of a watch. Titanium construction weighing just 4 grams.",
        "features": [
            "Titanium construction (4g)",
            "Sleep & readiness tracking",
            "Heart rate monitoring",
            "7-day battery life",
            "Water resistant to 100m",
        ],
        "image_url": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80&auto=format",
        "rating": 4.3,
        "reviews_count": 234,
        "in_stock": True,
        "badge": "New",
        "stock": 60,
    },
    {
        "name": "MagCharge Trio",
        "slug": "magcharge-trio",
        "price": 69.99,
        "category": "Accessories",
        "description": "3-in-1 magnetic wireless charging pad. Simultaneously charge your phone, earbuds, and smartwatch with perfect alignment every time.",
        "features": [
            "3-in-1 charging (phone, earbuds, watch)",
            "Magnetic alignment",
            "15W fast wireless charging",
            "LED charging indicators",
            "Non-slip silicone base",
        ],
        "image_url": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80&auto=format",
        "rating": 4.4,
        "reviews_count": 789,
        "in_stock": True,
        "badge": "",
        "stock": 120,
    },
    {
        "name": "Titanium USB-C Cable",
        "slug": "titanium-usb-c-cable",
        "price": 29.99,
        "category": "Accessories",
        "description": "Virtually indestructible braided USB-C cable with titanium connectors. 100W PD charging and 40Gbps data transfer in a 2-meter length.",
        "features": [
            "Titanium alloy connectors",
            "100W Power Delivery",
            "40Gbps USB4 data transfer",
            "Double-braided nylon jacket",
            "2-meter length",
        ],
        "image_url": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80&auto=format",
        "rating": 4.7,
        "reviews_count": 2341,
        "in_stock": True,
        "badge": "Best Seller",
        "stock": 300,
    },
    {
        "name": "AeroCase Ultra",
        "slug": "aerocase-ultra",
        "price": 49.99,
        "category": "Accessories",
        "description": "Ultra-thin phone case with military-grade drop protection. Aramid fiber construction at just 0.6mm thick with a matte, fingerprint-resistant finish.",
        "features": [
            "Aramid fiber construction",
            "0.6mm ultra-thin profile",
            "MIL-STD-810G drop tested",
            "Wireless charging compatible",
            "Matte fingerprint-resistant finish",
        ],
        "image_url": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80&auto=format",
        "rating": 4.5,
        "reviews_count": 1123,
        "in_stock": True,
        "badge": "",
        "stock": 90,
    },
    {
        "name": "PowerVault 20K",
        "slug": "powervault-20k",
        "price": 59.99,
        "category": "Accessories",
        "description": "20,000mAh portable power bank with 65W USB-C PD output — enough to charge your laptop. Digital display shows exact remaining capacity.",
        "features": [
            "20,000mAh capacity",
            "65W USB-C Power Delivery",
            "Charge 3 devices simultaneously",
            "Digital capacity display",
            "Pass-through charging",
        ],
        "image_url": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80&auto=format",
        "rating": 4.6,
        "reviews_count": 1876,
        "in_stock": True,
        "badge": "Sale",
        "stock": 150,
    },
    {
        "name": "Desk Organizer Pro",
        "slug": "desk-organizer-pro",
        "price": 39.99,
        "category": "Accessories",
        "description": "Minimalist desk organizer with integrated wireless charging pad, cable management, and device slots. Walnut wood and aluminum construction.",
        "features": [
            "Integrated 10W wireless charger",
            "Cable management channels",
            "Tablet & phone slots",
            "Walnut wood + aluminum build",
            "Non-scratch silicone base",
        ],
        "image_url": "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600&q=80&auto=format",
        "rating": 4.2,
        "reviews_count": 456,
        "in_stock": True,
        "badge": "",
        "stock": 70,
    },
    {
        "name": "Luma Smart Bulb Kit",
        "slug": "luma-smart-bulb-kit",
        "price": 89.99,
        "category": "Smart Home",
        "description": "Set of 4 smart RGB bulbs with 16 million colors and tunable white. No hub required — connects directly to Wi-Fi with voice assistant support.",
        "features": [
            "16 million colors + tunable white",
            "No hub required (Wi-Fi direct)",
            "Works with Alexa, Google, HomeKit",
            "Scheduling & sunrise simulation",
            "Energy monitoring",
        ],
        "image_url": "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=600&q=80&auto=format",
        "rating": 4.5,
        "reviews_count": 2234,
        "in_stock": True,
        "badge": "",
        "stock": 200,
    },
    {
        "name": "GuardCam 4K",
        "slug": "guardcam-4k",
        "price": 149.99,
        "category": "Smart Home",
        "description": "4K indoor/outdoor security camera with color night vision, AI person detection, and two-way audio. Local + cloud storage options.",
        "features": [
            "4K Ultra HD resolution",
            "Color night vision",
            "AI person & package detection",
            "Two-way audio with siren",
            "Local microSD + cloud storage",
        ],
        "image_url": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80&auto=format",
        "rating": 4.6,
        "reviews_count": 1345,
        "in_stock": True,
        "badge": "Best Seller",
        "stock": 45,
    },
    {
        "name": "HomeHub Mini",
        "slug": "homehub-mini",
        "price": 59.99,
        "category": "Smart Home",
        "description": "Compact smart home hub with a 4\" touchscreen display. Control all your smart devices, make video calls, and stream music from one central point.",
        "features": [
            '4" IPS touchscreen',
            "Zigbee, Z-Wave, Wi-Fi, Bluetooth",
            "Built-in speaker & mic",
            "Video calling",
            "Smart home dashboard",
        ],
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80&auto=format",
        "rating": 4.3,
        "reviews_count": 567,
        "in_stock": True,
        "badge": "",
        "stock": 55,
    },
    {
        "name": "ClimateSense Thermostat",
        "slug": "climatesense-thermostat",
        "price": 179.99,
        "category": "Smart Home",
        "description": "AI-powered smart thermostat that learns your schedule and preferences. Reduces energy bills by up to 23% while keeping your home perfectly comfortable.",
        "features": [
            "AI schedule learning",
            "Room-by-room temperature control",
            "Energy usage reports",
            "Geofencing auto-away",
            "Works with all HVAC systems",
        ],
        "image_url": "https://images.unsplash.com/photo-1545259742-b4fd8fea67e4?w=600&q=80&auto=format",
        "rating": 4.7,
        "reviews_count": 892,
        "in_stock": False,
        "badge": "",
        "stock": 0,
    },
    {
        "name": "AirPure Smart Purifier",
        "slug": "airpure-smart-purifier",
        "price": 229.99,
        "category": "Smart Home",
        "description": "HEPA air purifier with real-time air quality monitoring and auto-adjust fan speed. Covers up to 500 sq ft with whisper-quiet operation.",
        "features": [
            "True HEPA H13 filter",
            "Real-time PM2.5 & VOC monitoring",
            "Auto-adjust fan speed",
            "500 sq ft coverage",
            "Sleep mode at 22dB",
        ],
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80&auto=format",
        "rating": 4.4,
        "reviews_count": 678,
        "in_stock": True,
        "badge": "New",
        "stock": 35,
    },
]


class Command(BaseCommand):
    help = 'Seed the database with 20 premium tech products'

    def handle(self, *args, **options):
        created_count = 0
        for product_data in PRODUCTS:
            _, created = Product.objects.update_or_create(
                slug=product_data['slug'],
                defaults=product_data,
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done! {created_count} new products created, '
                f'{len(PRODUCTS) - created_count} updated.'
            )
        )
